pipeline {
    agent any
    stages {
        stage('Package') {
            steps {
            	echo 'Started Packaging'
                sh 'mvn clean install -Dmaven.test.skip=true'
                echo 'Packaging Completed'
            }
        }
        stage('Build Container') {
        	steps {
        		echo 'Started Building Container'
        		sh 'cp /var/lib/jenkins/workspace/configuration-registry -r .'
        		sh 'docker build -t configuration-server:1.0 -f Dockerfile .'
        		echo 'Completed Building Container'
        	}
        }
        stage('Publish Container') {
        	steps {
        		echo 'Started Publishing Container'
        		echo 'Completed Publishing Container'
        	}
        }
        stage('Running Container') {
        	steps {
        		echo 'Started Running Container'
        		sh 'docker run -p 8888:8888 -d configuration-server:1.0'
        		echo 'Completed Running Container'
        	}
        }
    }
    post {
    	always {
    		echo 'Clean Up'
    	}
    	success {
    		echo 'Deployment is Successful'
    	}
    	failure {
    		echo 'Deployment Failed'
    	}
    }
}